#define ELF_NOTE_NETBSD_NAMESZ 7
#define ELF_NOTE_NETBSD_DESCSZ 4
#define ELF_NOTE_TYPE_NETBSD_TAG 1
#define __NetBSD_Version__ 699001300
#define ELF_NOTE_PAX_NAMESZ 4
#define ELF_NOTE_PAX_DESCSZ 4
#define ELF_NOTE_TYPE_PAX_TAG 3
